line-length = 132

[lint]
select = [
  "F",  # Pyflakes
  "E",  # Pycodestyle Errors
  "W",  # Pycodestyle Warnings
  "I",  # isort
  "N",  # naming
  "UP",  # pyupgrade
  "PL",  # pylint
]
ignore = [
  "N818",  # Exception class names must end in "Error"
  "PLR2004",  # Magic value used in comparison
  "UP031", # Use format specifiers instead of percent format
]


[lint.isort]
force-sort-within-sections = true

[lint.pylint]
max-args = 6